spring:
  application:
    name: ChattingWebsite
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatting_website
    username: root
    password: '050598'
server:
  port: 4090
