spring:
  application:
    name: ChattingWebsite
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatting_website
    username: root
    password: '050598'
  servlet:
    multipart:
      #文件传输的大小上限
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  port: 4090

#自定义配置属性
rt:
  #存储文件的路径
  save-file-path: G:\Code Programming\SpringBoot_java\ChattingWebsite\uploadFile\
  #返回的请求文件的路径
  request-file-path: http://localhost:4090/files/download/
